### ISSUE TITLE
Trying to create an llm via HuggingFaceHub() but get "coroutine 'AsyncRunManager.on_text' was never awaited'

### ISSUE THREAD

**Issue by maspotts** [Future-House/paper-qa#113]
Hi: I'm trying to swap out:

`llm = ChatOpenAI(temperature = temperature, model_name = 'gpt-3.5-turbo', max_tokens = max_output_size)
`

with:

`llm = HuggingFaceHub(repo_id = 'mosaicml/mpt-7b-chat', model_kwargs = { "temperature": temperature, "max_length": max_output_size })
`

and then creating my index as usual via `index = Docs(llm = llm)`.  When I call `index.query()` with the index built with the `ChatOpenAI()` model it works, but when I call `index.query()` with the `HuggingFaceHub()` model I get this error:

```
/Users/mike/.pyenv/versions/3.10.7/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/llm.py:110: RuntimeWarning: coroutine 'AsyncRunManager.on_text' was never awaited
  run_manager.on_text(_text, end="\n", verbose=self.verbose)
```

(although I'm not calling `index.aquery()`).  Am I making an obvious mistake?  I'm hoping there's a nice simple way to make this work, so I can continue my successful implementation using paperqa!  Thanks in advance...

Mike

**Comment by whitead** [comment]
Try setting `key_filter = False` when you run `query`

**Comment by maspotts** [comment]
Thanks: tried it but got same error.

**Comment by whitead** [comment]
The "error" you're showing is just a warning. Are you sure there is not another exception?

**Comment by maspotts** [comment]
Ah, good point: I may have jumped the gun!  I had assumed something had gone fatally wrong because the process hangs after emitting the warning.  I've started it again and left it running; will see if it's completed or errored out or still hanging in the morning...

**Comment by maspotts** [comment]
OK here's the final exception:

**Comment by whitead** [comment]
Looks like the model timed out @maspotts - the open source models are a lot slower and paper-qa requires a lot of calls. I would recommend Claude or HuggingFace with a GPU instance if you're look to replace the OpenAI models. Llama can work too, but it's extremely slow

**Comment by maspotts** [comment]
Thanks: (off-topic but) do I need to upgrade to a paid huggingface tier to get sufficient performance?

**Comment by whitead** [comment]
Not sure, I have paid huggingface and I'm not sure what is available on free tier
