### ISSUE TITLE
OpenAI communication issue

### ISSUE THREAD

**Issue by rubayatkhan** [Future-House/paper-qa#136]
I have a paid account and my API key works on the HuggingFace demo, but when I try to call paperqa from my python code I'm getting the OpenAI communication failure and timeout:

openai.error.APIConnectionError: Error communicating with OpenAI

Kindly help!

**Comment by whitead** [comment]
Hard to say without more info. Note that sometimes OpenAI is overloeaded

**Comment by jamesbraza** [comment]
Hello @rubayatkhan  we have just released version 5, which completely outsources all LLM management (including OpenAI stuff) to https://github.com/BerriAI/litellm.

If your issue persists, please reopen a new issue using `paper-qa>=5`
