### ISSUE TITLE
OPENAI_API_KEY env variable check now occurs (and fails) on import of paperqa?

### ISSUE THREAD

**Issue by maspotts** [Future-House/paper-qa#149]
This is odd: I upgraded paperqa just now and then on the next run of my own project I got an error due to a missing openai_api_key.  But this error is being triggered from the `import paperqa` statement at the top of my python file.  Prior to this I've been able to create the `OPENAI_API_KEY` environment variable later in my code (before my first call to `paperqa.Docs()`) but it seems that just importing the module now triggers that check?  Is there a workaround?  I guess otherwise I'll have to move the import statement to after I create the `OPENAI_API_KEY` variable?

```
Traceback (most recent call last):
  File "/home/ec2-user/./chatbot-1.3.3", line 3, in <module>
    import paperqa
  File "/usr/local/python-modules/paperqa/__init__.py", line 1, in <module>
    from .docs import Answer, Docs, PromptCollection, Doc, Text
  File "/usr/local/python-modules/paperqa/docs.py", line 35, in <module>
    class Docs(BaseModel, arbitrary_types_allowed=True, smart_union=True):
  File "/usr/local/python-modules/paperqa/docs.py", line 43, in Docs
    llm: Union[str, BaseLanguageModel] = ChatOpenAI(
  File "/usr/local/python-modules/langchain/load/serializable.py", line 64, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
```

**Comment by nevin7771** [comment]
@whitead i have same issue, can you fix this ?

**Comment by whitead** [comment]
Working on this, as an immediate fix you can just set it to some fake value:

```sh
export OPENAI_API_KEY="sk-foo"
```

**Comment by maspotts** [comment]
checking but ran into another error (https://github.com/whitead/paper-qa/issues/152) so will check once I've got past that one...

**Comment by selva221724** [comment]
Use this below,  at the top of your script to initiate. This is worked for me. Now, I am getting an error, that I could not able to load the model `ggml-gpt4all-j-v1.3-groovy.bin` which is in my local. 

```
import os 
os.environ['OPENAI_API_KEY'] = 'dummy_key'
```

**Comment by cariaso** [comment]
try this for your model loading issue

pip install "llama-cpp-python==0.1.48"

**Comment by MoAh1** [comment]
I am running into a similar issue with the latest version of both langhchain and paper-qa.

**Comment by jamesbraza** [comment]
Hello everyone, we have just released version 5, which completely outsources all LLM management to https://github.com/BerriAI/litellm.

If your issue persists, please reopen a new issue using `paper-qa>=5`
