### ISSUE TITLE
system_prompt only used for OpenAI prompts

### ISSUE THREAD

**Issue by GordonMcGregor** [Future-House/paper-qa#198]
Looking at make_chain in chains, I see that the system prompt only makes it into the template for OpenAI LLMs.  

In particular this means that for other LLMs being used, this directive '"_Answer in a direct and concise tone, I am in a hurry. Your audience is an expert, so be highly specific. If there are ambiguous terms or acronyms, first define them_' is never passed.  I've seen some less-than-good acronyms in results for other LLMs, maybe as a result.

**Comment by whitead** [comment]
Good call - will see what we can do about that.

**Comment by jamesbraza** [comment]
Hi @GordonMcGregor , we have just released version 5, which exposes the system prompt for configuration. Also, it rewrites basically everything, so I am going to close this issue as resolved.

If your issue persists, please reopen a new issue using `paper-qa>=5`
