### ISSUE TITLE
Support adding multiple docs at once

### ISSUE THREAD

**Issue by jhohrath** [Future-House/paper-qa#208]
Currently, each document uploaded requires an API call to get embeddings. Due to API rate-limits, this really slows the document adding process for large corpus.

This process could be parallelized better by implementing a multiple document adding method, which aggregates texts across documents and sends them all to get embeddings in one API call.

**Comment by mskarlin** [comment]
Hi @jhohrath -- we've since parallelized both the embedding and document adding (especially when adding using the `async` API), let us know if you have any issues.
