### ISSUE TITLE
Cool work! Considering using a biomedical embedding model?

### ISSUE THREAD

**Issue by Andy-jqa** [Future-House/paper-qa#220]
Thank you for your wonderful work. It seems that the current system uses OpenAI's embedding models for dense retrieval, which might be sub-optimal (and costly). We have a biomedical embedding model trained by 255M real PubMed user logs. Would appreciate it if you could check out: 

Paper: https://academic.oup.com/bioinformatics/article/39/11/btad651/7335842
Query encoder: https://huggingface.co/ncbi/MedCPT-Query-Encoder
Article encoder:https://huggingface.co/ncbi/MedCPT-Article-Encoder

**Comment by zacsims** [comment]
@Andy-jqa I would like to use MedCPT as the embedding model here, but it is my understanding that PaperQA uses the same embedding model for the query and documents. In this case, which of the three MedCPT models would you recommend using here?

**Comment by Andy-jqa** [comment]
> @Andy-jqa I would like to use MedCPT as the embedding model here, but it is my understanding that PaperQA uses the same embedding model for the query and documents. In this case, which of the three MedCPT models would you recommend using here?

Thanks! MedCPT has separate query and document encoders that are only trained with their respective data distribution. If only one embedding model can be used, I would not recommend using MedCPT, as the query encoder won't work well with documents and vice versa.
