### ISSUE TITLE
Install doesn't complete with python 3.12

### ISSUE THREAD

**Issue by kfletcherelo** [Future-House/paper-qa#224]
Using python 3.12 I obtained the following error:
```
  Building wheel for faiss-cpu (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for faiss-cpu (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [93 lines of output]
...
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for faiss-cpu
Failed to build faiss-cpu
ERROR: Could not build wheels for faiss-cpu, which is required to install pyproject.toml-based projects
```

This could be fixed by downgrading python to 3.9 (see https://github.com/kyamagu/faiss-wheels/issues/80)

I recommend updating the README.md to state which versions of Python the software has been tested with.

**Comment by jhrcook** [comment]
Can confirm that installation was unsuccessful with 3.12 but successful with Python v3.11.6 (on an M2 Mac).

**Comment by jamesbraza** [comment]
We have just released version 5, which no longer depends upon faiss. So I am going to close this out.

If you issue still persists, please reopen a new issue using `paper-qa>=5`
