### ISSUE TITLE
Docs class doesn't work with GoogleGenerativeAIEmbeddings embeddings

### ISSUE THREAD

**Issue by ekcomputer** [Future-House/paper-qa#226]
After some inspection, it appears that the `Docs` class may have no keyword option for an embeddings object and is hard-coded to use the `OpenAIEmbeddings` by default, as follows:

https://github.com/whitead/paper-qa/blob/84f13ea32c22b85924cd681a4b5f4fbd174afd71/paperqa/docs.py#L56

The README implies that `Docs` can be initialized with `LlamaCppEmbeddings`, however, when I try this with `GoogleGenerativeAIEmbeddings`, I get an error from the pydantic library not recognizing the `GoogleGenerativeAIEmbeddings` as a valid embeddings type :

```python
Exception has occurred: ValidationError
1 validation error for Docs
embeddings
  instance of Embeddings expected (type=type_error.arbitrary_type; expected_arbitrary_type=Embeddings)
  File "/Users/ekyzivat/Library/CloudStorage/Dropbox/Python/LLM-packages/tmp/paperqa_literature_table_workflow.py", line 42, in <module>
    docs = Docs(llm=model, embeddings=Embeddings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic.error_wrappers.ValidationError: 1 validation error for Docs
embeddings
  instance of Embeddings expected (type=type_error.arbitrary_type; expected_arbitrary_type=Embeddings)
```
Is this an issue with paper-q or pydantic?

**Comment by jamesbraza** [comment]
Hello @ekcomputer, this issue looks to be that `GoogleGenerativeAIEmbeddings` is not considered a valid embedding type. We possibly will need to either:
- Update our README docs to make this more clear
- Update the allowable types in `Docs`

We have just released version 5, which completely outsources all LLM management to https://github.com/BerriAI/litellm and rewrites the README. If your issue persists, can you please reopen a new issue using `paper-qa>=5`?
