### ISSUE TITLE
ues installing paper-qa

### ISSUE THREAD

**Issue by VaticanCameos99** [Future-House/paper-qa#228]
I am running paper-qa in a conda environment. I tried installing the library using pip but I get a ModuleNotFoundError when trying to import it. 
I then just cloned the repo and used it. and on running the example under the Usage section I get the following error:

Traceback (most recent call last):
  File "/Users/username/envname/model1/simple_paperqa.py", line 4, in <module>
    from paperQA.paperqa import Docs
  File "/Users/username/envname/model1/paperQA/paperqa/__init__.py", line 1, in <module>
    from .docs import Answer, Docs, PromptCollection, Doc, Text, Context
  File "/Users/username/envname/model1/paperQA/paperqa/docs.py", line 9, in <module>
    from openai import AsyncOpenAI
ImportError: cannot import name 'AsyncOpenAI' from 'openai' (/Users/username/anaconda3/envs/envname/lib/python3.10/site-packages/openai/__init__.py)

I tried reinstalling openai but it doesn't resolve the issue.

**Comment by jamesbraza** [comment]
We have totally changed our dependencies in today's v5 release. If you still have installation/setup issues with v5, please open a new issue
