### ISSUE TITLE
Usage with Google Gemini

### ISSUE THREAD

**Issue by Kamrulhasan12345** [Future-House/paper-qa#234]
Hi,
I tried to use google gemini with paper-qa using the `ChatGoogleGenerativeAI(modeol='gemini-pro')` from `langchain_google_genai` using the 2nd sample of ChatAnthropic(). If I setup API key correctly, then I see `self.name = client.model_name` error in llms.py file. If I fix that line in the llms.py to client.name / client.model (can't exactly remember), I see a `NoneType` error from grpc.

Moreover, due to many other issues, I am not able to run llama.cpp(with embedding one as LlamaEmbedding..) one too. I face pydantic name error for LlamaEmbedding... function at the first try. But if I give any name, I get another pydantic error with some NoneType thing while in `[type=in..., (h_...., ),....]` If I remove the entire embedding, I see `File Not Found` error while accessing the api, whereas I can easily access the api from localhost:8080. And in the logs, I see 404 in llamafile when paperqa requests.

I also tried using the old v3 llama accessing one. But that ends with some other errors for me.

**I am doing all these from Github Codespaces**

Why could these be occuring?

**Comment by jamesbraza** [comment]
Hello @Kamrulhasan12345, we have just released version 5, which completely outsources all LLM management to https://github.com/BerriAI/litellm.

If your issue persists, please reopen a new issue using `paper-qa>=5`
