### ISSUE TITLE
Decompose get_evidence

### ISSUE THREAD

**Issue by whitead** [Future-House/paper-qa#283]
We'd like to decompose get_evidence into two pure functions:

1. retrieve - which retrieves from a vector store according to some config and returns `Texts`
2. map - the current process function that executes a function with a semaphore over multiple `Texts` and returns `Contexts`

Then we'll create a `map_factory` that converts an enum to a specific map function. The first ones will be `map_summary_json` and `map_summary_text`.

Finally, we'll revise `get_evidence` to simply call these other functions. These other functions will live in some new module of `pqa_fxnl` or some better name.

**Comment by whitead** [comment]
@SamCox822 @jamesbraza @mskarlin please take a look and let me know if you have feedback!

**Comment by jamesbraza** [comment]
Thanks and I like it. I think the name `pqa_fxnl` is a bit awk, imagine `from paperqa.pqa_fxnl import foo` (there's duplication of pqa). Maybe alternate names are `core` or `functional`.

My "spec" to contribute is just making sure we postpone all input arg mutations until after all model calls (e.g. vector store lookups, LLM calls) have been run. That way callers can safely retry upon things like transient model provider errors

**Comment by whitead** [comment]
Additional items:

1. Get rid of `get_callbacks` and just check if `name` is callback `kwargs`, if so apply it
2. Separate configs into answer/parse/prompts
3. Make `Docs` be only collection of docs. Maybe call it `DocSet` to avoid ambiguity
4. Remove all `Docs` methods to be thin wrappers to core functions:

- [ ] adoc_match: retrieve_docs
- [X] gather_evidence: retrieve_texts, map_llm
- [ ] generate_answer: filter, reduce_llm

5. Add example w comprehensive: search, map_llm

**Comment by whitead** [comment]
Decided for various reasons that we still need to track things through a whole request, necessitating stateful Answer objects. We took a step in #289, but I think we'll need to rethink this plan.
