### ISSUE TITLE
Getting a lot of python packages version mismatch ...

### ISSUE THREAD

**Issue by bhamadicharef** [Future-House/paper-qa#299]
Anyone is able to make paper-qa work just by a pip install paper-qa ?

I am getting a lot of python packages version mismatch ...

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qubo-nn 0.2.5 requires tensorflow, which is not installed.
tensorboard 2.14.0 requires protobuf>=3.19.6, which is not installed.
tensorflow-datasets 2.1.0 requires protobuf>=3.6.1, which is not installed.
wandb 0.12.10 requires protobuf>=3.12.0, which is not installed.
lightning 2.0.8 requires pydantic<2.2.0,>=1.7.4, but you have pydantic 2.2.0 which is incompatible.
pyppeteer 1.0.2 requires urllib3<2.0.0,>=1.25.8, but you have urllib3 2.2.2 which is incompatible.
pytorch-lightning 0.9.0 requires tensorboard==2.2.0, but you have tensorboard 2.14.0 which is incompatible.
selenium 4.1.0 requires urllib3[secure]~=1.26, but you have urllib3 2.2.2 which is incompatible.
yaspin 2.1.0 requires termcolor<2.0.0,>=1.1.0, but you have termcolor 2.4.0 which is incompatible.

the dev-requirement.txt does not include any specific version for each packages ...

Brahim @ Singapore

**Comment by whitead** [comment]
Each commit to the paper-qa repo does a clean install. Judging from your error messages - you have some other packages installed (e.g., tensorflow, wandb, pypeteer) which are not part of paper-qa that are conflicting with each other, rather than paper-qa

**Comment by bhamadicharef** [comment]
Thanks !
