### ISSUE TITLE
How to use OpenAI api key with base url in paperqa?

### ISSUE THREAD

**Issue by eyeqwe** [Future-House/paper-qa#307]
### I am having trouble getting openai api key with a base url to work  in paperqa. Any help in this regard would be appreciated. 
Or maybe if there's a provision to get mistral api key to work, that would be great too.**

from paperqa import Docs
from azure.identity import DefaultAzureCredential, get_bearer_token_provider, InteractiveBrowserCredential, ManagedIdentityCredential, ClientSecretCredential
from openai import AzureOpenAI
import openai

openai.api_key = AzureOpenAI(
    api_key="e----------------------------B",
    api_version="---------------preview",
    azure_endpoint="https://------------------openai-gpt")

my_docs = ['/home/-------------------/test_pdf_1.pdf']
docs = Docs()
for d in my_docs:
    docs.add(d)
answer = docs.query(
    "What are the key objectives of this thesis?"
)
print(answer.formatted_answer)

### this code is obviously erroneous, help me rectify it please. TIA**

**Comment by jamesbraza** [comment]
Hello @eyeqwe, we have just released version 5, which completely outsources all LLM management to [BerriAI/litellm](https://github.com/BerriAI/litellm).

If you issue persists, please reopen a new issue using `paper-qa>=5`
