### ISSUE TITLE
File sample PDF not working

### ISSUE THREAD

**Issue by ricardoborges** [Future-House/paper-qa#32]
[apollo.pdf](https://github.com/whitead/paper-qa/files/10974067/apollo.pdf)
I can't get any answer from this file, I don't know why... maybe too many images?

**Comment by whitead** [comment]
Not sure - can you give me some specific questions?

**Comment by ricardoborges** [comment]
like "what was the crew of Apollo 8?"

**Comment by jamesbraza** [comment]
Hello @ricardoborges , we have just released version 5, which basically rewrites everything and comes with step function performance improvements.

If your issue persists, can you please reopen a new issue with a minimal repro code snippet using `paper-qa>=5`?

**Comment by ricardoborges** [comment]
thanks! this is great news!
