### ISSUE TITLE
Error Code 404

### ISSUE THREAD

**Issue by thedimpop** [Future-House/paper-qa#397]
Not sure what I'm doing wrong but this is the error message I get when trying to run pqa ask:

 NotFoundError: litellm.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model 
           `gpt-4o-2024-08-06` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 
           'code': 'model_not_found'}}
           Received Model Group=gpt-4o-2024-08-06
           Available Model Group Fallbacks=None

**Comment by taabishm2** [comment]
Do you have funds added to the account associated with the OpenAI API key? If yes, I would try creating a new key and testing with it.

**Comment by thedimpop** [comment]
@taabishm2 thank you.  I'm making progress. Now looks like I'm hitting 30k TPM limit even when only 1 paper is in the folder. Relevant Papers=1 | Current Evidence=14, but the answer is blank. Is 30k TPM not enough to process such request?

**Comment by jamesbraza** [comment]
Hi @thedimpop we are working on figuring out rate limits in https://github.com/Future-House/paper-qa/issues/377

Since it looks like your OpenAI key issue is resolved here, do you mind if I consolidate the TPM limit stuff on https://github.com/Future-House/paper-qa/issues/377?

**Comment by whitead** [comment]
This should be fixed by latest release and setting to use `tier1_limits` (or equiv tier)
