### ISSUE TITLE
Not possible to get Crossref API Key - This tool is no longer available

### ISSUE THREAD

**Issue by DanKoan** [Future-House/paper-qa#412]
https://www.crossref.org/deprecated/

any suggestion for substitution of Crossref?

**Comment by jamesbraza** [comment]
Crossref as a whole isn't deprecated, that page is seemingly a place where Crossref documents various aspects of its overall service that have been deprecated.

Was there some aspect of our code that made you observe a deprecation notice?

**Comment by hogmeade** [comment]
From here: https://api.crossref.org/swagger-ui/index.html. Look like they dont provide the api key any more but instead just use https protocol. So how can I set up the crossref api in the settings? I tried to process 42 pdfs. Do I need to get these api?
