### ISSUE TITLE
environment issue

### ISSUE THREAD

**Issue by FahaxikiHoney** [Future-House/paper-qa#449]
Hello, can you provide the environmental requirements for this project?

**Comment by FahaxikiHoney** [comment]
Can you provide the versions of the various dependency libraries? I encountered library errors when running the project.

**Comment by FahaxikiHoney** [comment]
When I run the following code, an error occurred. the error is  that ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
from paperqa import Settings

**Comment by FahaxikiHoney** [comment]
How can I properly configure my Python virtual environment?

**Comment by FahaxikiHoney** [comment]
ModuleNotFoundError: No module named 'paperqa.version'

**Comment by jamesbraza** [comment]
Hi @FahaxikiHoney I think your issue is with environmment set up, please see https://github.com/Future-House/paper-qa/issues/443
