### ISSUE TITLE
ImportError: cannot import name 'Settings' from 'paperqa'

### ISSUE THREAD

**Issue by zhiyiZeng** [Future-House/paper-qa#455]
Hello, I encountered an ImportError while trying to import the Settings class from the paperqa package. Below are the details of the issue:
![image](https://github.com/user-attachments/assets/d857c6aa-cf16-47ab-8d79-edd500be6217)

I've tried in both windows and linux. I appreciate any help.

**Comment by zhiyiZeng** [comment]
not working. I install version 4.9 using pip. I'm trying to install from souce. However, I'm not finding any setup file in this project. How to install from souce?

**Comment by zhiyiZeng** [comment]
this project has no setup file, how is that possible to install it from source?

**Comment by jamesbraza** [comment]
Hi @zhiyiZeng I think the issue is you need paper-qa version 5. The `settings` module didn't exist before then in versions such as version 4.

Can you `pip install -U paper-qa` or `pip install paper-qa>=5` to get version 5

**Comment by habema** [comment]
Hello @jamesbraza 

I am running into the same issue, and can't seem to find any installation candidates for `paper-qa>=5` using pip

Here is my output:
```
❯ pip --version
pip 24.2 from /home/hiro/testing_paper_qa/venv/lib/python3.10/site-packages/pip (python 3.10)
❯ pip index versions paper-qa
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
paper-qa (4.9.0)
Available versions: 4.9.0, 4.8.1, 4.8.0, 4.7.0, 4.6.1, 4.6.0, 4.5.2, 4.5.1, 4.5.0, 4.4.1, 4.4.0, 4.3.0, 4.2.1, 4.2.0, 4.1.1, 4.1.0, 4.0.0, 3.13.4, 3.13.3, 3.13.2, 3.13.1, 3.13.0, 3.12.0, 3.11.2, 3.11.1, 3.11.0, 3.10.0, 3.9.1, 3.9.0, 3.8.0, 3.7.1, 3.7.0, 3.6.0, 3.5.0, 3.4.1, 3.4.0, 3.3.3, 3.3.2, 3.3.1, 3.3.0, 3.2.1, 3.2.0, 3.1.1, 3.1.0, 3.0.0, 2.1.1, 2.1.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.12.0, 1.11.0, 1.10.0, 1.9.0, 1.8.0, 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.4.1, 1.4.0, 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0, 0.1.0, 0.0.21, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
```

**Comment by habema** [comment]
Hello @zhiyiZeng

I was just running into the same issue and solved it by upgrading python3.10 to 3.11.

**Comment by zhiyiZeng** [comment]
@habema Thanks, it solves my problem. I install the package using the latest `.whl`  file and the error message suggests that I need to use Python 3.11, just like what you said. Also appreciate your help @jamesbraza for building this wondereful package.
