### ISSUE TITLE
No module named 'paperqa.version'

### ISSUE THREAD

**Issue by SURUIYUAN** [Future-House/paper-qa#457]
Why show  “ModuleNotFoundError: No module named 'paperqa.version' “

**Comment by SURUIYUAN** [comment]
Please explain in detail

**Comment by janzheng** [comment]
If you're working on the source files, I added

`from .version import __version__ ` to `__init.py` about the `from paperqa.agents import ask  # noqa: E402` line.

I also added a `/paperqa/version.py` with a single line: `__version__ = "5.0.10"`

I come from JS-land so I have no idea if this is what you're "supposed" to do, but it fixed my problems!

**Comment by maykcaldas** [comment]
Hey @SURUIYUAN and @janzheng 

The current paperqa version can be checked with `paperqa.__version__`

I believe this is an old issue. Therefore, I'm closing it. Please feel free to reopen it if the issue has not been answered.
