### ISSUE TITLE
Implement CLI Functionality

### ISSUE THREAD

**Issue by malekinho8** [Future-House/paper-qa#69]
It would be nice to have a CLI that can be run to automatically enter the question-answering routine. The app should be installable through the setup.py and be created using the `click` package. Example of desired behavior pasted below:

```
qa-pdf [pdf_file]
```

**Comment by marioseixas** [comment]
https://github.com/whitead/paper-qa/issues/286

**Comment by jamesbraza** [comment]
This is now implemented as part of v5, see: https://github.com/Future-House/paper-qa/tree/v5.0.0?tab=readme-ov-file#cli
