### ISSUE TITLE
Slow query times

### ISSUE THREAD

**Issue by malekinho8** [Future-House/paper-qa#70]
During the query process where the user can find the answer to their question, the time to obtain the chatgpt response as well as retrieving evidence can be significant. It would be nice to be able to set up the context retrieval and answer creation process more efficiently, similar to the waiting times in [askyourpdf.com](https://askyourpdf.com/).

**Comment by jamesbraza** [comment]
Hello @malekinho8, we have just released version 5, which completely outsources all LLM management to https://github.com/BerriAI/litellm. I think also modern day LLMs like `gpt-4o` are much faster.

So I am going to close this out, please reopen a new issue using `paper-qa>=5` if it persists. Also, you'll need to provide a repro of your issues and/or timings desired
