### ISSUE TITLE
Problem defining EnvironmentState?

### ISSUE THREAD

**Issue by reubendocea** [Future-House/paper-qa#732]
There is some issue setting up the EnvironmentState, but there isn't guidance on how to do this in the set-up instructions?

Python 3.12 with paper-qa version 5.5   

> (python3.12) pqa ask 'Summarise this research'
> 
> Traceback (most recent call last):
>   File "/mnt/cluster/environments/doceareub/miniconda3/envs/312generic/bin/pqa", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/mnt/cluster/environments/doceareub/miniconda3/envs/312generic/lib/python3.12/site-packages/paperqa/agents/__init__.py", line 224, in main
>     settings = Settings.from_name(
>                ^^^^^^^^^^^^^^^^^^^
>   File "/mnt/cluster/environments/doceareub/miniconda3/envs/312generic/lib/python3.12/site-packages/paperqa/settings.py", line 783, in from_name
>     tmp = Settings.model_validate_json(json_path.read_text())
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/cluster/environments/doceareub/miniconda3/envs/312generic/lib/python3.12/site-packages/pydantic/main.py", line 656, in model_validate_json
>     return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/cluster/environments/doceareub/miniconda3/envs/312generic/lib/python3.12/site-packages/pydantic/_internal/_mock_val_ser.py", line 100, in __getattr__
>     raise PydanticUserError(self._error_message, code=self._code)
> pydantic.errors.PydanticUserError: `Settings` is not fully defined; you should define `EnvironmentState`, then call `Settings.model_rebuild()`.
> 
> For further information visit https://errors.pydantic.dev/2.10/u/class-not-fully-defined

**Comment by reubendocea** [comment]
Seems to work with paper-qa version 5.2

**Comment by jamesbraza** [comment]
Yes @reubendocea thanks for the report, we are on this.

https://github.com/Future-House/paper-qa/pull/590 introduced the issue in version 5.3 (which is why 5.2 works), but we didn't realize it until Pydantic 2.10 started ensuring `TYPE_CHECKING` was not used. @nadolskit made the fix for this in https://github.com/Future-House/paper-qa/pull/725, and it should be released shortly.

If you want to use v5.5, you just need to use `pydantic<2.10`.
