### ISSUE TITLE
Parsing JSON error when increasing evidence_k with mixtral:8x7b

### ISSUE THREAD

**Issue by Snikch63200** [Future-House/paper-qa#736]
Hello,

I paperQA returns a JSON parsing error when I increase evidence_k when I use mixtral:7xb ass LLM model.

Works fine with these parameters : 

```
settings.answer.answer_max_sources = 5 
settings.answer.evidence_k = 10  
```

Doesn't works with these parameters : 

```
settings.answer.answer_max_sources = 5 
settings.answer.evidence_k = 20  
```

Returns this error : 

```
    return json.loads(ptext)
           ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 2 column 14 (char 15)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XXXXXXXXXX\Desktop\PaperQA\paper_qa_question_sync.py", line 126, in <module>
    my_query()
  File "C:\Users\XXXXXXXXXX\Desktop\PaperQA\paper_qa_question_sync.py", line 104, in my_query
    answer = docs.query(
             ^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\paperqa\docs.py", line 665, in query
    return get_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\paperqa\docs.py", line 705, in aquery
    session = await self.aget_evidence(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\paperqa\docs.py", line 632, in aget_evidence
    results = await gather_with_concurrency(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\paperqa\utils.py", line 114, in gather_with_concurrency
    return await asyncio.gather(*(sem_coro(c) for c in coros))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\paperqa\utils.py", line 112, in sem_coro
    return await coro
           ^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\paperqa\core.py", line 78, in map_fxn_summary
    result_data = parser(context) if parser else {}
                  ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\paperqa\core.py", line 31, in llm_parse_json
    raise ValueError(
ValueError: Failed to parse JSON from text ' {\n  "summary": "The excerpt provides information about a study of silver coins from the '. Your model may not be capable of supporting JSON output or our parsing technique could use some work. Try a different model or specify `Settings(prompts={'use_json': False})`
```

Works fine, with llama3.1:70b with these parameters : 

```
settings.answer.answer_max_sources = 5 
settings.answer.evidence_k = 20  
```

Does anyone have an idea about this issue ?

@dosu.

**Comment by jamesbraza** [comment]
Hi @Snikch63200, looking at the stack:

> ValueError: Failed to parse JSON from text ' {\n  "summary": "The excerpt provides information about a study of silver coins from the '. Your model may not be capable of supporting JSON output or our parsing technique could use some work. Try a different model or specify `Settings(prompts={'use_json': False})`

Specifically:

> from text ' {\n  "summary": "The excerpt provides information about a study of silver coins from the '

You can see the model seems to have truncated the JSON, there is no closing brace `}`. Perhaps your `max_tokens` was too low, or `mixtral:8x7b` isn't able to produce JSON reliably

**Comment by jamesbraza** [comment]
@Snikch63200 yeah if you look at the error message:

> Try a different model or specify `Settings(prompts={'use_json': False})`

You can try this out, basically it moves "evidence" from JSON to just text blobs

**Comment by Snikch63200** [comment]
Hello,

I tried to specify `Settings(prompts={'use_json': False})` but it gives poor results.

But I solved this issue (that's not a paperqa issue).

It seems Llama3.1 accepts -1 or -2 as `num_predict` value (-1 = infinite token generation, -2 context len token generation) while mixtral:8x7b doesn't. So I set up `num_predict` to 1E6 and it work fine.

Thanks for you help.

**Comment by jamesbraza** [comment]
Thanks for sharing your resolution, appreciated.

> PS : Maybe it's good idea to open a discussion about LLMs optimal configuration settings for PaperQA. I'll try to get time to write a short synthesis abour my own experience with several models.

We do have a couple pre-made settings in [`paperqa/configs`](https://github.com/Future-House/paper-qa/tree/v5.7.0/paperqa/configs), feel free to open an issue requesting changes to one or more.

Also, I expanded https://github.com/Future-House/paper-qa/issues/749 to get retrying cover this case as well, I am going to close this out, thanks for the report
