### ISSUE TITLE
how to make the software work using the released file?

### ISSUE THREAD

**Issue by fengan078525** [Future-House/paper-qa#83]
How to make the software work using the released file?
![无标题](https://user-images.githubusercontent.com/131636258/234010220-61d0802c-3346-4e78-a311-bbf2ce11c641.png)
Can some one kindly help me?

**Comment by jamesbraza** [comment]
We publish this as a Python package to PyPI: https://pypi.org/project/paper-qa/

We don't expose binaries directly within our GitHub releases, those are mainly for a changelog.

You can install from PyPI following these instructions: https://github.com/Future-House/paper-qa/tree/v5.0.0?tab=readme-ov-file#install
