### ISSUE TITLE
OpenAI API Alternative

### ISSUE THREAD

**Issue by neeewwww** [Future-House/paper-qa#98]
Hello! Do you see any alterantive to use an Open Source Free alternative to OpenAI API?

**Comment by whitead** [comment]
Yup - [see here](https://github.com/whitead/paper-qa#locally-hosted)

**Comment by neeewwww** [comment]
Sorry, I'm dumb... Gonna give it try. I'm completely illiterate with coding and trying to build like Lego using ChatGPT.

**Comment by neeewwww** [comment]
Can you provide some kind of tutorial on how to change the LLM?

**Comment by jamesbraza** [comment]
Hello @neeewwww thanks for this. I think this is done in v5 here: https://github.com/Future-House/paper-qa/tree/v5.0.0?tab=readme-ov-file#choosing-model

Going to close this out. Feel free to open a new issue if you have further questions
